groups:
- name: app_alerts
  rules:
  - alert: HighErrorRate
    expr: rate(processing_errors_total[5m]) > 0.1
    for: 5m
    labels:
      severity: warning
  - alert: ServiceDown
    expr: up == 0
    for: 1m
    labels:
      severity: critical