global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'doener_service'
    static_configs:
      - targets: ['doener_service:8082']

  - job_name: 'invoice_service'
    static_configs:
      - targets: ['invoice_service:8083']

  - job_name: 'order_service'
    static_configs:
      - targets: ['order_service:8081']

  - job_name: 'frontend_service'
    static_configs:
      - targets: ['frontend_service:8080']

  - job_name: 'rabbitmq'
    metrics_path: /metrics
    static_configs:
      - targets: ['rabbitmq:15692']

rule_files:
  - prometheus-rules.yml