global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'doener_service'
    static_configs:
      - targets: ['doener_service:8001']

  - job_name: 'invoice_service'
    static_configs:
      - targets: ['invoice_service:8002']

  - job_name: 'order_service'
    static_configs:
      - targets: ['order_service:8003']

  - job_name: 'frontend_service'
    static_configs:
      - targets: ['frontend_service:8004']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
